[package]
name = "lp2lnd"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
build = "build.rs"

[features]
default = []
tokio-console = ["dep:console-subscriber"]

[dependencies]
lp2ln-core-v2 = { path = "../lp2ln-core-v2" }
lp2ln-release = { path = "../lp2ln-release" }
sha2 = "0.10.8"
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0.89"
serde_json = "1.0"
base64 = "0.22"
futures-util = "0.3"
tokio-tungstenite = "0.23"
console-subscriber = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
tokio-util = { version = "0.7", features = ["rt"] }

[build-dependencies]
winresource = "0.1"

[dev-dependencies]
lp2ln-app-sdk = { path = "../lp2ln-app-sdk" }

[[bin]]
name = "lp2lnd"
path = "src/main.rs"

[[bin]]
name = "lp2lnd-scale"
path = "src/scale_daemon.rs"
